language: java
env:
  global:
    - "FTP_USER=developer"
    - "FTP_PASSWORD=admin"
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD sftp://squandered.org/java-projects/"
